% Build a cascade (row vector) of RF elements
elements(1) = amplifier(NF=25);
elements(2) = modulator( ...
    NF=20, ...
    OIP3=30, ...
    LO=11e9);
elements(3) = amplifier( ...
    Gain=5, ...
    NF=15, ...
    OIP3=30);
elements(4) = modulator( ...
    Gain=-6, ...
    NF=15, ...
    OIP3=25, ...
    LO=66e9);
elements(5) = amplifier( ...
    Gain=9, ...
    NF=15, ...
    OIP3=30);
elements(6) = rffilter( ...
    'FilterType','Butterworth', ...
    'ResponseType','Bandstop', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'StopbandFrequency',[51 55]*1e9, ...
    'StopbandAttenuation',40, ...
    'Zin',100, ...
    'Zout',50, ...
    'Name','Filter');
elements(7) = amplifier( ...
    Gain=10, ...
    NF=25, ...
    OIP3=37);
elements(8) = attenuator('Attenuation',4);

% Construct an rfbudget object
b = rfbudget( ...
    Elements=elements, ...
    InputFrequency=0, ...
    AvailableInputPower=0, ...
    SignalBandwidth=116e6, ...
    Solver='Friis', ...
    AutoUpdate=0);
