% Build a cascade (row vector) of RF elements
elements(1) = attenuator('Attenuation',4);
elements(2) = amplifier( ...
    Name='LNA', ...
    Gain=15, ...
    NF=8, ...
    OIP3=15);
elements(3) = rffilter( ...
    'FilterType','Chebyshev', ...
    'ResponseType','Bandstop', ...
    'Implementation','LC Tee', ...
    'FilterOrder',3, ...
    'PassbandAttenuation',3, ...
    'StopbandFrequency',[51 55]*1e9, ...
    'StopbandAttenuation',40, ...
    'Zin',50, ...
    'Zout',50, ...
    'Name','Filter');
elements(4) = amplifier( ...
    Gain=8, ...
    NF=10, ...
    OIP3=20);
elements(5) = modulator( ...
    Name='Demodulator', ...
    Gain=-6, ...
    NF=15, ...
    OIP3=25, ...
    LO=66e9, ...
    ConverterType='Down');
elements(6) = amplifier( ...
    Gain=8, ...
    NF=20, ...
    OIP3=30);
elements(7) = modulator( ...
    Name='Demod', ...
    NF=20, ...
    OIP3=30, ...
    LO=11e9, ...
    ConverterType='Down');
elements(8) = amplifier( ...
    Name='ADC_12bit', ...
    NF=25);

% Construct an rfbudget object
b = rfbudget( ...
    Elements=elements, ...
    InputFrequency=77e9, ...
    AvailableInputPower=-20, ...
    SignalBandwidth=116e6, ...
    Solver='Friis', ...
    AutoUpdate=0);
